import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'zh' | 'ja' | 'es' | 'fr';

export const translations = {
  en: {
    app_title: "Voxpeb",
    nav_home: "Overview",
    nav_shell: "Shell Studio",
    nav_brain: "Brain Builder",
    hero_badge: "Embodied AI English Coach",
    hero_title_1: "A Language Tutor",
    hero_title_2: "Living in Your Pocket",
    hero_desc: "Voxpeb solves the distraction of phone-based learning. Build your own physical AI companion based on M5Stack Core2. Customize its body (Voxel 3D) and its brain (Personality).",
    btn_design: "Design Appearance",
    btn_firmware: "Configure Firmware",
    feat_1_title: "Phone-free Focus",
    feat_1_desc: "Create a low-anxiety environment. No notifications, no apps. Just you and your physical companion.",
    feat_2_title: "Embodied Cognition",
    feat_2_desc: "Tactile interaction reduces stress. Holding the device transforms 'learning pressure' into playful interaction.",
    feat_3_title: "Hyper-customization",
    feat_3_desc: "Don't just choose a voice. Build the body and define the soul. Create an emotional attachment that drives consistency.",
    model_title: "Pocket Monster Shell Studio",
    model_desc: "Design a custom case for your M5Stack Core S3. We generate a pocket-sized monster/Pokemon 3D model with a perfect 54mm x 54mm cavity for the screen.",
    input_label: "Monster Description",
    input_placeholder: "e.g., A cute electric yellow mouse monster with red cheeks, lightning tail, voxel style",
    opt_print: "Auto-fits 54mm M5Stack Core S3",
    pipeline_title: "Pipeline (Automated)",
    step_1: "Text to Image (T2I)",
    step_1_d: "Gemini/Imagen generates multi-view voxel draft.",
    step_2: "Image to 3D (I23D)",
    step_2_d: "Converts 2D to rough Voxel mesh.",
    step_3: "Hardware Integration",
    step_3_d: "Carves out 54x54mm socket for M5Stack Core S3.",
    btn_generate: "Generate Model",
    loading_gen: "Summoning Monster...",
    retry: "Retry",
    download_stl: "Download .STL",
    stl_note: "Download includes Base Template (60mm box)",
    preview_empty: "Preview will appear here",
    firmware_title: "Firmware 'Brain' Builder",
    firmware_desc: "Configure the personality, pedagogical approach, and constraints. We'll generate the dedicated firmware file (.bin).",
    identity: "Identity",
    robot_name: "Robot Name",
    voice_neutral: "Neutral Helper",
    voice_energetic: "Energetic Kid",
    voice_deep: "Deep & Wise",
    voice_soft: "Soft & Gentle",
    personality: "Personality",
    pers_strict: "Strict",
    pers_encouraging: "Encouraging",
    pers_humorous: "Humorous",
    pers_serious: "Serious",
    pedagogy: "Pedagogy",
    corr_style: "Correction Style",
    corr_imm: "Immediate Interrupt",
    corr_sum: "End-of-chat Summary",
    corr_ser: "Major Errors Only",
    level: "Level",
    level_adap: "Adaptive (i+1)",
    btn_compile: "Generate Firmware",
    btn_compiling: "Compiling Brain...",
    preview_file: "system_prompt_preview.txt",
    download_bin: "Download .bin",
    brain_empty: "Configure parameters and click Generate to preview the AI brain.",
    footer_copy: "Voxpeb (语珀) © 2025",
    footer_power: "Powered by Google Gemini 2.5 Flash & M5Stack Core2"
  },
  zh: {
    app_title: "语珀 (Voxpeb)",
    nav_home: "概览",
    nav_shell: "外观工坊",
    nav_brain: "大脑构建",
    hero_badge: "具身智能英语教练",
    hero_title_1: "你的专属语言导师",
    hero_title_2: "生活在口袋里",
    hero_desc: "Voxpeb 解决了手机学习分心的问题。基于 M5Stack Core2 构建你自己的物理 AI 伴侣。自定义它的身体（体素 3D）和大脑（个性）。",
    btn_design: "设计外观",
    btn_firmware: "配置固件",
    feat_1_title: "无手机专注",
    feat_1_desc: "创造低焦虑环境。没有通知，没有应用。只有你和你的物理伴侣。",
    feat_2_title: "具身认知",
    feat_2_desc: "触觉互动减少压力。手持设备将“学习压力”转化为有趣的互动。",
    feat_3_title: "超高度定制",
    feat_3_desc: "不仅仅是选择声音。构建身体并定义灵魂。建立情感依恋以推动持续性。",
    model_title: "口袋怪物外观工坊",
    model_desc: "为您的 M5Stack Core S3 设计定制外壳。我们生成带有完美 54mm x 54mm 屏幕嵌入槽的口袋妖怪风格 3D 模型。",
    input_label: "怪物描述",
    input_placeholder: "例如：一个可爱的黄色电气鼠怪物，红脸蛋，闪电尾巴，体素风格",
    opt_print: "自动适配 54mm M5Stack Core S3",
    pipeline_title: "自动化管线",
    step_1: "文生图 (T2I)",
    step_1_d: "Gemini/Imagen 生成多视角体素草图。",
    step_2: "图生 3D (I23D)",
    step_2_d: "将 2D 转换为粗糙体素网格。",
    step_3: "硬件集成",
    step_3_d: "为 M5Stack Core S3 预留 54x54mm 槽位。",
    btn_generate: "生成模型",
    loading_gen: "正在召唤怪物...",
    retry: "重试",
    download_stl: "下载 .STL",
    stl_note: "下载文件为基础适配模版 (60mm盒)",
    preview_empty: "预览将在此处显示",
    firmware_title: "固件“大脑”构建器",
    firmware_desc: "配置个性、教学方法和约束条件。我们将生成专用的固件文件 (.bin)。",
    identity: "身份",
    robot_name: "机器人名称",
    voice_neutral: "中性助手",
    voice_energetic: "充满活力的孩子",
    voice_deep: "深沉智慧",
    voice_soft: "温柔轻柔",
    personality: "个性",
    pers_strict: "严格",
    pers_encouraging: "鼓励",
    pers_humorous: "幽默",
    pers_serious: "严肃",
    pedagogy: "教学法",
    corr_style: "纠错风格",
    corr_imm: "立即打断",
    corr_sum: "对话结束总结",
    corr_ser: "仅主要错误",
    level: "等级",
    level_adap: "自适应 (i+1)",
    btn_compile: "生成固件",
    btn_compiling: "正在编译大脑...",
    preview_file: "系统提示词预览.txt",
    download_bin: "下载 .bin",
    brain_empty: "配置参数并点击生成以预览 AI 大脑。",
    footer_copy: "Voxpeb (语珀) © 2025",
    footer_power: "由 Google Gemini 2.5 Flash & M5Stack Core2 驱动"
  },
  ja: {
    app_title: "Voxpeb",
    nav_home: "概要",
    nav_shell: "シェルスタジオ",
    nav_brain: "ブレインビルダー",
    hero_badge: "具現化AI英語コーチ",
    hero_title_1: "言語チューターが",
    hero_title_2: "あなたのポケットに",
    hero_desc: "Voxpebはスマホ学習の気が散る問題を解決します。M5Stack Core2ベースの物理AIコンパニオンを作成しましょう。ボディ（ボクセル3D）と脳（性格）をカスタマイズ。",
    btn_design: "外観をデザイン",
    btn_firmware: "ファームウェア設定",
    feat_1_title: "スマホフリーの集中",
    feat_1_desc: "低不安環境を作成。通知なし、アプリなし。あなたと物理コンパニオンだけ。",
    feat_2_title: "身体性認知",
    feat_2_desc: "触覚的な相互作用がストレスを軽減。デバイスを持つことで「学習プレッシャー」を遊びに変えます。",
    feat_3_title: "超カスタマイズ",
    feat_3_desc: "声を選ぶだけではありません。体を構築し、魂を定義します。愛着を形成し、継続性を促進します。",
    model_title: "ポケモン風シェルスタジオ",
    model_desc: "M5Stack Core S3用のカスタムケースをデザインします。54mm x 54mmの画面埋め込みスペースを持つポケットモンスター風の3Dモデルを生成します。",
    input_label: "モンスターの説明",
    input_placeholder: "例：赤い頬と稲妻の尻尾を持つかわいい電気ネズミのモンスター、ボクセルスタイル",
    opt_print: "54mm M5Stack Core S3に自動適合",
    pipeline_title: "パイプライン (自動)",
    step_1: "テキストから画像 (T2I)",
    step_1_d: "Gemini/Imagenが多視点ボクセルドラフトを生成。",
    step_2: "画像から3D (I23D)",
    step_2_d: "2Dを粗いボクセルッシュに変換。",
    step_3: "ハードウェア統合",
    step_3_d: "M5Stack Core S3用に54x54mmのスロットを切り出します。",
    btn_generate: "モデルを生成",
    loading_gen: "モンスターを召喚中...",
    retry: "再試行",
    download_stl: ".STLをダウンロード",
    stl_note: "ベーステンプレート（60mmボックス）をダウンロード",
    preview_empty: "プレビューはここに表示されます",
    firmware_title: "ファームウェア「脳」ビルダー",
    firmware_desc: "性格、教育学的アプローチ、制約を設定します。専用のファームウェアファイル(.bin)を生成します。",
    identity: "アイデンティティ",
    robot_name: "ロボット名",
    voice_neutral: "中立的なヘルパー",
    voice_energetic: "元気な子供",
    voice_deep: "深く賢明",
    voice_soft: "ソフトで優しい",
    personality: "性格",
    pers_strict: "厳格",
    pers_encouraging: "励ます",
    pers_humorous: "ユーモラス",
    pers_serious: "真面目",
    pedagogy: "教育法",
    corr_style: "修正スタイル",
    corr_imm: "即時中断",
    corr_sum: "チャット終了時の要約",
    corr_ser: "主要なエラーのみ",
    level: "レベル",
    level_adap: "適応型 (i+1)",
    btn_compile: "ファームウェア生成",
    btn_compiling: "脳をコンパイル中...",
    preview_file: "システムプロンプトプレビュー.txt",
    download_bin: ".binをダウンロード",
    brain_empty: "パラメータを設定し、生成をクリックしてAI脳をプレビューします。",
    footer_copy: "Voxpeb (语珀) © 2025",
    footer_power: "Google Gemini 2.5 Flash & M5Stack Core2 によって提供"
  },
  es: {
    app_title: "Voxpeb",
    nav_home: "Resumen",
    nav_shell: "Estudio de Diseño",
    nav_brain: "Constructor de Cerebro",
    hero_badge: "Entrenador de Inglés IA",
    hero_title_1: "Un Tutor de Idiomas",
    hero_title_2: "Viviendo en tu Bolsillo",
    hero_desc: "Voxpeb resuelve la distracción del aprendizaje basado en el teléfono. Construye tu propio compañero físico de IA basado en M5Stack Core2. Personaliza su cuerpo (Voxel 3D) y su cerebro (Personalidad).",
    btn_design: "Diseñar Apariencia",
    btn_firmware: "Configurar Firmware",
    feat_1_title: "Enfoque sin teléfono",
    feat_1_desc: "Crea un entorno de baja ansiedad. Sin notificaciones, sin aplicaciones. Solo tú y tu compañero físico.",
    feat_2_title: "Cognición Encarnada",
    feat_2_desc: "La interacción táctil reduce el estrés. Sostener el dispositivo transforma la 'presión de aprendizaje' en interacción lúdica.",
    feat_3_title: "Hiper-personalización",
    feat_3_desc: "No solo elijas una voz. Construye el cuerpo y define el alma. Crea un apego emocional que impulsa la consistencia.",
    model_title: "Estudio de Monstruos 3D",
    model_desc: "Diseña un estuche personalizado para tu M5Stack Core S3. Generamos un modelo 3D de monstruo/Pokemon con una cavidad perfecta de 54mm x 54mm.",
    input_label: "Descripción del Monstruo",
    input_placeholder: "ej., Un monstruo ratón eléctrico amarillo lindo con mejillas rojas, estilo voxel",
    opt_print: "Ajuste automático M5Stack 54mm",
    pipeline_title: "Tubería (Automatizada)",
    step_1: "Texto a Imagen (T2I)",
    step_1_d: "Gemini/Imagen genera borrador de voxel multi-vista.",
    step_2: "Imagen a 3D (I23D)",
    step_2_d: "Convierte 2D a malla de voxel rugosa.",
    step_3: "Integración de Hardware",
    step_3_d: "Crea ranura de 54x54mm para M5Stack.",
    btn_generate: "Generar Modelo",
    loading_gen: "Invocando Monstruo...",
    retry: "Reintentar",
    download_stl: "Descargar .STL",
    stl_note: "Descarga incluye Plantilla Base (caja 60mm)",
    preview_empty: "La vista previa aparecerá aquí",
    firmware_title: "Constructor de Firmware",
    firmware_desc: "Configura la personalidad, el enfoque pedagógico y las restricciones. Generaremos el archivo de firmware dedicado (.bin).",
    identity: "Identidad",
    robot_name: "Nombre del Robot",
    voice_neutral: "Ayudante Neutral",
    voice_energetic: "Niño Enérgico",
    voice_deep: "Profundo y Sabio",
    voice_soft: "Suave y Gentil",
    personality: "Personalidad",
    pers_strict: "Estricto",
    pers_encouraging: "Alentador",
    pers_humorous: "Humorístico",
    pers_serious: "Serio",
    pedagogy: "Pedagogía",
    corr_style: "Estilo de Corrección",
    corr_imm: "Interrupción Inmediata",
    corr_sum: "Resumen al final",
    corr_ser: "Solo errores mayores",
    level: "Nivel",
    level_adap: "Adaptativo (i+1)",
    btn_compile: "Generar Firmware",
    btn_compiling: "Compilando Cerebro...",
    preview_file: "vista_previa_sistema.txt",
    download_bin: "Descargar .bin",
    brain_empty: "Configura parámetros y haz clic en Generar para previsualizar el cerebro de IA.",
    footer_copy: "Voxpeb (语珀) © 2025",
    footer_power: "Desarrollado por Google Gemini 2.5 Flash & M5Stack Core2"
  },
  fr: {
    app_title: "Voxpeb",
    nav_home: "Aperçu",
    nav_shell: "Studio de Coque",
    nav_brain: "Constructeur de Cerveau",
    hero_badge: "Coach d'Anglais IA Incarné",
    hero_title_1: "Un Tuteur de Langue",
    hero_title_2: "Vivant dans votre Poche",
    hero_desc: "Voxpeb résout la distraction de l'apprentissage sur téléphone. Construisez votre propre compagnon IA physique basé sur M5Stack Core2. Personnalisez son corps (Voxel 3D) et son cerveau (Personnalité).",
    btn_design: "Concevoir l'Apparence",
    btn_firmware: "Configurer le Firmware",
    feat_1_title: "Concentration sans téléphone",
    feat_1_desc: "Créez un environnement à faible anxiété. Pas de notifications, pas d'applications. Juste vous et votre compagnon physique.",
    feat_2_title: "Cognition Incarnée",
    feat_2_desc: "L'interaction tactile réduit le stress. Tenir l'appareil transforme la 'pression d'apprentissage' en interaction ludique.",
    feat_3_title: "Hyper-personnalisation",
    feat_3_desc: "Ne choisissez pas seulement une voix. Construisez le corps et définissez l'âme. Créez un attachement émotionnel qui favorise la régularité.",
    model_title: "Studio de Monstres 3D",
    model_desc: "Concevez une coque personnalisée pour votre M5Stack Core S3. Nous générons un modèle 3D de style monstre/Pokemon avec une cavité parfaite de 54mm x 54mm.",
    input_label: "Description du Monstre",
    input_placeholder: "ex., Un mignon monstre souris électrique jaune avec des joues rouges, style voxel",
    opt_print: "Ajustement auto M5Stack 54mm",
    pipeline_title: "Pipeline (Automatisé)",
    step_1: "Texte vers Image (T2I)",
    step_1_d: "Gemini/Imagen génère un brouillon voxel multi-vues.",
    step_2: "Image vers 3D (I23D)",
    step_2_d: "Convertit la 2D en maillage voxel grossier.",
    step_3: "Intégration Matérielle",
    step_3_d: "Crée une fente de 54x54mm pour M5Stack Core S3.",
    btn_generate: "Générer le Modèle",
    loading_gen: "Invocation du Monstre...",
    retry: "Réessayer",
    download_stl: "Télécharger .STL",
    stl_note: "Le téléchargement inclut le modèle de base (boîte de 60 mm)",
    preview_empty: "L'aperçu apparaîtra ici",
    firmware_title: "Constructeur de Firmware",
    firmware_desc: "Configurez la personnalité, l'approche pédagogique et les contraintes. Nous générerons le fichier de firmware dédié (.bin).",
    identity: "Identité",
    robot_name: "Nom du Robot",
    voice_neutral: "Assistant Neutre",
    voice_energetic: "Enfant Énergique",
    voice_deep: "Profond & Sage",
    voice_soft: "Doux & Gentil",
    personality: "Personnalité",
    pers_strict: "Strict",
    pers_encouraging: "Encourageant",
    pers_humorous: "Humoristique",
    pers_serious: "Sérieux",
    pedagogy: "Pédagogie",
    corr_style: "Style de Correction",
    corr_imm: "Interruption Immédiate",
    corr_sum: "Résumé de fin de chat",
    corr_ser: "Erreurs majeures seulement",
    level: "Niveau",
    level_adap: "Adaptatif (i+1)",
    btn_compile: "Générer Firmware",
    btn_compiling: "Compilation du Cerveau...",
    preview_file: "aperçu_invite_système.txt",
    download_bin: "Télécharger .bin",
    brain_empty: "Configurez les paramètres et cliquez sur Générer pour prévisualiser le cerveau IA.",
    footer_copy: "Voxpeb (语珀) © 2025",
    footer_power: "Propulsé par Google Gemini 2.5 Flash & M5Stack Core2"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations['en']) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};